### ISSUE TITLE
Sodalite 1.4.0 causing massive preloader error

### ISSUE THREAD

**Issue by GrigoriSpankov** [H3VR-Modding/Sodalite#11]
This occurs when no mods (other than sodalite's dependencies) are active, ruling out a conflict, and on any version; beta, alpha or otherwise. It completely prevents BepIn from loading any of my currently installed mods. I don't have much technical know-how, so I am just going to send the error message to you and see what you think. Thanks.
![error](https://user-images.githubusercontent.com/115088830/194611883-6e54115a-413c-4a84-a9fc-5327bca1b232.png)

**Comment by GrigoriSpankov** [comment]
I am starting to become worried about this. The release of Openscripts 2, which relies on this version of Sodalite exclusively, could slowly begin to replace the original Openscripts, with mods either being updated to replace the old with the new or newer mods being made for that version specifically. That would mean I would basically be locked out completely from downloading new mods. Please, for the love of **GOD**, investigate this. I don't want to be left behind.

**Comment by GrigoriSpankov** [comment]
Here is the log file, running with only three other mods: BepInExPack_H3VR, MonoMod_Loader and HookGenPatcher_H3VR.
[preloader_20221016_213956_207.log](https://github.com/H3VR-Modding/Sodalite/files/9795636/preloader_20221016_213956_207.log)

**Comment by nrgill28** [comment]
I've left this issue open for a while to see if anyone else was experiencing the same thing, and it doesn't appear like that is the case. 

Can you confirm that you have an otherwise unmodified version of the game installed from Steam? By that I mean you have not made any manual modifications to the game or it's files outside of the standard mod installation methods (r2modman / Thunderstore Mod Manager).

**Comment by GrigoriSpankov** [comment]
I did try to (unsuccessfully) install ReShade, but other than that I've not done anything. I've been talking with PrimeVR recently; he's not experiencing the issue and is telling me to do a fresh install of R2 and H3VR. I'm gonna try that.

**Comment by GrigoriSpankov** [comment]
After performing a complete reinstall, the preloader error has now completely disappeared. Thanks to PrimeVR for that suggestion.
