### ISSUE TITLE
Logic bug with sosig API equipment spawning

### ISSUE THREAD

**Issue by devyndamonster** [H3VR-Modding/Sodalite#6]
In the sosig API, the logic for spawning equipment based on random chance is inverted. In the `Spawn` method, you make the following comparisons:
```
// Spawn the secondary weapon
bool spawnWithSecondaryWeapon = spawnOptions.EquipmentMode.HasFlag(SpawnOptions.EquipmentSlots.Secondary) && Random.Range(0.0f, 1f) >= template.SecondaryChance;
```

The problem is the last part: `Random.Range(0.0f, 1f) >= template.SecondaryChance;`

When the secondary chance is 1, the secondary equipment will never spawn
This is also true for tertiary equipment

**Comment by nrgill28** [comment]
Fixed in [9d9769](https://github.com/H3VR-Modding/Sodalite/commit/9d97693be599b73a0f693133b46816e471b29fa1), will be included in the next release.
